source "https://rubygems.org"

gem "dotenv", "~> 3.1"
gem "dry-equalizer", "~> 0.3.0"
gem "faraday", "~> 2.9"
gem "faraday-follow_redirects", "~> 0.3.0"
gem "nokogiri", "~> 1.16"
gem "opentelemetry-exporter-otlp", "~> 0.26.3"
gem "opentelemetry-instrumentation-all", "~> 0.60.0"
gem "opentelemetry-sdk", "~> 1.4"
gem "parallel", "~> 1.24"
gem "pony", "~> 1.13"
gem "rake", "~> 13.2"
gem "ruby-openai", "~> 7.0"
gem "tilt", "~> 2.3"
gem "watir", "~> 7.3"
